### ISSUE TITLE
fail to connect to ssh server

### ISSUE THREAD

**Issue by slashmili** [jbenden/esshd#1]
I followed the steps but I got this error message when I'm trying to connect to server

```
ssh -p 10022 tests@127.0.0.1
ssh_exchange_identification: Connection closed by remote host
```

Elixir/Erlang version: 

```
Erlang/OTP 20 [erts-9.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
```

**Comment by jbenden** [comment]
Hello,

As a part of the install, in one of the middle steps you should have placed an `authorized_keys` file in to the `priv` directory.

In order to connect successfully, the private key file for which the public matching key that was listed inside of the `authorized_keys` file needs to be passed with your `ssh` command-line arguments.

Try something like the following:

```
ssh -i <YOUR PRIVATE KEY FILE> -p 10022 tests@127.0.0.1
```

If you are unable to connect, then please run the above command with an added `-vvvvv` argument and post the output to this bug report.

Best Regards,
-Joe

**Comment by slashmili** [comment]
Hey @jbenden,

The files in my `priv` dir:
```
ls  priv/
authorized_keys        ssh_host_ecdsa_key     ssh_host_ecdsa_key.pub
```

```
ssh -vvvvv -i ~/.ssh/id_rsa -p 10022 tests@127.0.0.1
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "127.0.0.1" port 10022
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 10022.
debug1: Connection established.
debug1: identity file /Users/milad/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/milad/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
ssh_exchange_identification: Connection closed by remote host
```

**Comment by slashmili** [comment]
All the tests also fail on my machine.

for example:
```
mix test
Compiling 1 file (.ex)


  1) test when remotely connecting it does nothing with an invalid command (SshdTest)
     test/esshd_test.exs:35
     ** (MatchError) no match of right hand side value: {:error, 'Connection closed'}
     code: {:ok, conn, chan_id} = SSHClient.connect ip: @ip, port: @port, user: @user, password: @pass
     stacktrace:
       test/test_helper.exs:20: SSHClient.connect/1
       test/esshd_test.exs:36: (test)
```

**Comment by jbenden** [comment]
Hello,

It turns out that permissions of files and directories are probably wrong, along with a required missing host key.

Please run the following script inside of the root of your project:

```
#!/usr/bin/env bash

set -euf

[ -d priv ] || mkdir priv

chmod 700 priv

cd priv

echo "===> Please press ENTER/RETURN for *ALL* passphrase entries!!!!!"

ssh-keygen -b 256 -t ecdsa -f ssh_host_ecdsa_key
ssh-keygen -b 1024 -t dsa -f ssh_host_dsa_key
ssh-keygen -b 2048 -t rsa -f ssh_host_rsa_key

echo 127.0.0.1,127.0.0.1 `cat ssh_host_ecdsa_key.pub` > known_hosts
chmod 644 known_hosts

echo "Please copy a valid public key to the 'priv/authorized_keys' file"

exit 0
```

Please note: In testing this myself, everything worked for authentication. However, upon connecting everything fails in attempting to spawn an Elixir or Erlang shell. The reasoning is that a simple application has no supervisor tree and no way to keep a connection alive upon connect. So a more than basic simple application is needed to fully test.

Best Regards,
-Joe

**Comment by slashmili** [comment]
Works now 👍 

Thanks!

**Comment by ku1ik** [comment]
@jbenden I have followed all the steps from readme to start Elixir REPL, but I'm getting the following error:

```[info] authenticate under #PID<0.1473.0>
[info] authenticate under #PID<0.1473.0>
[warn] Exception caught
[error] Process #PID<0.1480.0> raised an exception
** (MatchError) no match of right hand side value: {:error, :terminated}
    (iex) lib/iex.ex:744: anonymous fn/2 in IEx.start/2
```

This looks to me like something related to what you said about fail to spawn Elixir shell.

Is this misconfiguration on my part, or do I have to add some additional code to make IEx successfully start?

**Comment by ku1ik** [comment]
I tried with `Sshd.ShellHandler.Erlang` too and it also errors out. However `Sshd.ShellHandler.Example` works fine. So do I understand it correctly that `IEx.start` starts a new process which starts some child, but it exits itself, and Esshd tries to communicate whe the original IEx process which is no longer there?
